version: '3.8'

services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    networks:
      - laravel-network


networks:
  laravel-network:
    external: true
