version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8003:80"
    volumes:
      - ./app:/var/www/html/app
      - ./resources:/var/www/html/resources
      - ./config:/var/www/html/config
      - ./database:/var/www/html/database
      - ./tests:/var/www/html/tests
      - ./routes:/var/www/html/routes 
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock 
    environment:
      DB_CONNECTION: mysql
      DB_HOST: product-db
      DB_PORT: 3306
      DB_DATABASE: product_db
      DB_USERNAME: root
      DB_PASSWORD: secret
    networks:
      - laravel-network
    depends_on:
      - product-db

  product-db:
    image: mysql:5.7
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: product_db
    ports:
      - "33063:3306"
    networks:
      - laravel-network

networks:
  laravel-network:
    external: true
