version: '3.8'

services:
  shopping-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopping-service
    ports:
      - "8002:80"
    volumes:
      - ./app:/var/www/html/app
      - ./resources:/var/www/html/resources
      - ./config:/var/www/html/config
      - ./database:/var/www/html/database
      - ./tests:/var/www/html/tests
      - ./routes:/var/www/html/routes 
    environment:
      DB_CONNECTION: mysql
      DB_HOST: shopping-db
      DB_PORT: 3306
      DB_DATABASE: shopping_db
      DB_USERNAME: root
      DB_PASSWORD: secret
    networks:
      - laravel-network
    depends_on:
      - shopping-db

  shopping-db:
    image: mysql:5.7
    container_name: shopping-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: shopping_db
    ports:
      - "33062:3306"
    networks:
      - laravel-network

networks:
  laravel-network:
    external: true
